### ISSUE TITLE
Dependency Compatibility Issue

### ISSUE THREAD

**Issue by josejlm2** [baibaratsky/yii2-rollbar#10]
Just updated to newest version (`v1.6.1`) but the the line 
`rollbar/rollbar": "^1.3.3,` 
causes the Rollbar dependency to update to `v1.4.0` which creates errors in the application. 
The new Rollbar version seems to be asking for a new constant called `IS_UNCAUGHT_KEY`

Rolling back to `v1.6.0` seems to be a temporary solution for now. 

Rolling back to 
![capture](https://user-images.githubusercontent.com/3478468/36110806-99b70ed6-0fe9-11e8-939f-d3aeef5186b2.PNG)

**Comment by baibaratsky** [comment]
I was afraid of this and used to describe dependencies with `~`. But merging #9 I was thinking that the guys from Rollbar make minor updates backward compatible and also that @lgelfan had tested his pull request.
Thank you for the report and sorry for this problem. I’m going to fix it right now.

**Comment by lgelfan** [comment]
Sorry about that, I did test on my environment which updated Rollbar to 1.3.6. I did see that 1.4 was included as a future release which is why I used the caret notation -- and also assumed minor releases wouldn't have any breaking changes. Guess we'll have to fix the Rollbar releases to patch level.

**Comment by gelige** [comment]
Looks like ~1.3.3 constraint doesn't fix the issue, rollbar-php 1.3.6 has no constant, but fits the dependency requirement

**Comment by baibaratsky** [comment]
Oh really? That’s very strange what guys from Rollbar are doing.

**Comment by ekzobrain** [comment]
This constant has gone away in 1.3.2, so the latest working version is 1.3.1, not 1.3.3!

**Comment by ekzobrain** [comment]
https://github.com/rollbar/rollbar-php/blob/v1.3.1/src/Utilities.php
https://github.com/rollbar/rollbar-php/blob/v1.3.2/src/Utilities.php

**Comment by baibaratsky** [comment]
Thanks @soulhunter1987
