### ISSUE TITLE
Not compatible with PHP 7.2

### ISSUE THREAD

**Issue by niektenhoopen** [baibaratsky/yii2-rollbar#12]
Hi @baibaratsky, your module is not compatible with PHP 7.2 because it uses yii\base\Object. Yii2 changed this classname to yii\base\BaseObject in 2.0.13: https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

What would be the ideal solution? Require Yii 2.0.13+ in composer and then extend from BaseObject?

**Comment by baibaratsky** [comment]
Hi! I think your proposal should work. Could you make a PR with it?
