### ISSUE TITLE
Callback for ignoring exceptions

### ISSUE THREAD

**Issue by friek108** [baibaratsky/yii2-rollbar#15]
IgnoreExceptions is great, gives great control... however for API rollbar tracking, an invalid response will be returned as json like the below:

    {"name":"Unauthorized","message":"Your request was made with invalid credentials.","code":0,"status":401}

Would it be possible to add in maybe a callback to determine if a request should be sent to rollbar?

**Comment by baibaratsky** [comment]
I’m not sure this issue is related to ignoreExceptions. Looks like the access key is incorrect.
