### ISSUE TITLE
Exception 'Exception' with message 'Level '' doesn't exist.' 

### ISSUE THREAD

**Issue by klytron** [baibaratsky/yii2-rollbar#18]
2018-05-07 21:41:27 [197.251.181.44][-][-][warning][yii\log\Dispatcher::dispatch] Unable to send log 
    via baibaratsky\yii\rollbar\log\Target: Exception 'Exception' with message 'Level '' doesn't exist.' 

    in /home/yii2/vendor/rollbar/rollbar/src/Payload/Level.php:42

    Stack trace:
    #0 /home/yii2/vendor/baibaratsky/yii2-rollbar/log/Target.php(22): 
    Rollbar\Payload\Level::__callStatic('fromName', Array)
    #1 /home/yii2/vendor/yiisoft/yii2/log/Target.php(133): 
      baibaratsky\yii\rollbar\log\Target->export()
    #2 /home/yii2/vendor/yiisoft/yii2/log/Dispatcher.php(189): yii\log\Target->collect(Array, true)
    #3 /home/yii2/vendor/yiisoft/yii2/log/Logger.php(177): yii\log\Dispatcher->dispatch(Array, true)
    #4 [internal function]: yii\log\Logger->flush(true)
    #5 {main}

in my controller i called 
`\Yii::info($message);`

**Comment by klytron** [comment]
I found this issue; https://github.com/rollbar/rollbar-php/issues/244

**Comment by baibaratsky** [comment]
Fixed in #16

**Comment by baibaratsky** [comment]
Use [v1.7.1](https://github.com/baibaratsky/yii2-rollbar/releases/tag/v1.7.1) to have this fix applied.
