### ISSUE TITLE
Log level 'info'

### ISSUE THREAD

**Issue by bot4343** [baibaratsky/yii2-rollbar#2]
In my config:

```
'rollbar' => [
                    'class' => 'baibaratsky\yii\rollbar\log\Target',
                    'levels' => ['error', 'warning'], // Log levels not contain "info" (!)
                ],
```

But in **Rollbar** I have INFO notification like `#54 $_COOKIE = [`
How to remove their from?

**Comment by baibaratsky** [comment]
Hello!
This is context messages generated by the Yii2 \yii\log\Target class. You can implement your own behavior in a child class. Look at https://github.com/yiisoft/yii2/blob/50cd3e1123a7461a672fc2be857ffad5d85104b4/framework/log/Target.php#L106
