### ISSUE TITLE
Ignore Exceptions is NOT working

### ISSUE THREAD

**Issue by poonga** [baibaratsky/yii2-rollbar#24]
I used this plugin in my Yii2 project. Ignore exception configuration is not working. This is my configuration
``` 
'rollbar' => [
            'class' => 'baibaratsky\yii\rollbar\Rollbar',
            'accessToken' => env('ROLLBAR_POST_SERVER_ITEM'),
            'environment' => env('ROLLBAR_ENVIRONMENT'),
            'ignoreExceptions' => [
                ['yii\web\HttpException', 'statusCode' => [400, 404]],
                ['yii\web\HttpException', 'statusCode' => [403], 'message' => ['This action is forbidden']],
        ], 
```
Screenshot of rollbar account page
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/32412021/81639758-7f1f6780-943a-11ea-982b-9c1dd0191167.png">

Can anyone please help me to ignore 404, 403 errors and bot request?

**Comment by baibaratsky** [comment]
The config looks good. You could dump some variables and debug this part of the code to have an idea what’s happening.
https://github.com/baibaratsky/yii2-rollbar/blob/master/ErrorHandlerTrait.php#L75
