### ISSUE TITLE
Rollbar v.4 support

### ISSUE THREAD

**Issue by crystinutzaa** [baibaratsky/yii2-rollbar#28]
Hey 

It seems that Rollbar released the latest version of the plugin on  Mar 20, 2023: v4.x.
https://github.com/rollbar/rollbar-php/tags

This plugin seems to be tied to the previous version 
`"rollbar/rollbar": "^3.1"`

Could be possible to upgrade it?

**Comment by baibaratsky** [comment]
Sure. Please create a PR for that.On 16 Jan 2024, at 09:15, Cristina Soponar ***@***.***> wrote:﻿
Hey
It seems that Rollbar released the latest version of the plugin on  Mar 20, 2023: v4.x.
https://github.com/rollbar/rollbar-php/tags
This plugin seems to be tied to the previous version
"rollbar/rollbar": "^3.1"
Could be possible to upgrade it?
