### ISSUE TITLE
Protected exception property

### ISSUE THREAD

**Issue by MUlt1mate** [baibaratsky/yii2-rollbar#3]
When message property is defined in ignoreExceptions method \baibaratsky\yii\rollbar\ErrorHandlerTrait::logException throws **Cannot access protected property yii\web\BadRequestHttpException::$message**
`'ignoreExceptions' => [
                ['\Exception', 'message' => ['{"statusCode":400}']],
],`

**Comment by baibaratsky** [comment]
Right, that's because the message property has protected visibility and can't be accessed outside of the class.

**Comment by MUlt1mate** [comment]
But you have `message` property in your example

**Comment by baibaratsky** [comment]
I've got another class. As a kind of solution, you may create a child exception class with a public property.
