### ISSUE TITLE
API error: Invalid format. data.body must not be undefined.

### ISSUE THREAD

**Issue by sluchznak** [baibaratsky/yii2-rollbar#4]
Hello.
API error: Invalid format. data.body must not be undefined. Instead, it should be an object with a 'message', 'trace', 'trace_chain', or 'crash_report' key.

tried different versions:
baibaratsky/yii2-rollbar:1.4.\* (rollbar-php:0.18.2)
baibaratsky/yii2-rollbar:1.1.0 (rollbar-php:0.15.0)

**Comment by baibaratsky** [comment]
It‘s hard to determine from this report what‘s your problem. Be sure that’s something wrong with your code, we‘re running this extension on our production servers and don‘t have such errors.
