### ISSUE TITLE
Compatibility problem in php 7

### ISSUE THREAD

**Issue by ezoterik** [baibaratsky/yii2-rollbar#5]
If an application throws ParseError then this extension makes fatal error:

> Uncaught TypeError: Argument 1 passed to baibaratsky\yii\rollbar\web\ErrorHandler::getPayloadData() must be an instance of Exception, instance of ParseError given, called in /var/www/app/vendor/baibaratsky/yii2-rollbar/ErrorHandlerTrait.php on line 44 and defined in /var/www/app/vendor/baibaratsky/yii2-rollbar/ErrorHandlerTrait.php:64

**Comment by baibaratsky** [comment]
@ezoterik Please confirm that the problem is fixed in the master branch.

**Comment by ezoterik** [comment]
@baibaratsky Yes, it works. Thank you for this update!
