### ISSUE TITLE
Support for Rollbar 1.x?

### ISSUE THREAD

**Issue by lgelfan** [baibaratsky/yii2-rollbar#7]
Trying to update Rollbar from 0.18.x to 1.x and I get:

`baibaratsky/yii2-rollbar v1.5.0 requires rollbar/rollbar ~0.18.0 -> satisfiable by rollbar/rollbar[v0.18.0, v0.18.2] but these conflict with your requirements or minimum-stability.`

Are there plans to support Rollbar 1.x?

Thanks.

**Comment by baibaratsky** [comment]
You don’t need to require rollbar/rollbar explicitly in your composer.json.
If you need v1 support, feel free to submit a pull request.

**Comment by baibaratsky** [comment]
Fixed in #8
